#!/bin/bash

fil="./3100_kernel_underclocking.patch"

cat >"$fil" <<EOF
this was applied on top of kernel 4.2.rc4.r0.gcbfe8fa-1
and 4.3.rc1.r217.g00ade1f-1

EOF

diff -up kernel/smp.c.orig kernel/smp.c >> "$fil"

